services:
  app:
    build: .
    container_name: chronicler
    restart: always
    network_mode: "host"
    volumes:
    - ./app:/app
    - ./data:/data
    working_dir: /app

    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: python main.py
