version: '3.8'

services:
  app:
    build: .
    container_name: chronicler
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: python bot.py
